import type { OsrsItem } from "./types";

// Stub vocabulary for testing. Full item list (~3,800 items) would be
// generated by tools/generate-osrs-vocab.ts from the OSRS wiki /mapping endpoint.
export const OSRS_ITEMS: OsrsItem[] = [
  { id: 4151, name: "Abyssal Whip", nameLower: "abyssal whip" },
  { id: 11802, name: "Armadyl Godsword", nameLower: "armadyl godsword" },
  { id: 12696, name: "Twisted Bow", nameLower: "twisted bow" },
  { id: 1351, name: "Bronze Axe", nameLower: "bronze axe" },
  { id: 1267, name: "Iron Axe", nameLower: "iron axe" },
  { id: 1269, name: "Steel Axe", nameLower: "steel axe" },
  { id: 1373, name: "Dragon Axe", nameLower: "dragon axe" },
  { id: 1745, name: "Dragon Hide", nameLower: "dragon hide" },
  { id: 2497, name: "Granite Maul", nameLower: "granite maul" },
  { id: 1079, name: "Rune Platelegs", nameLower: "rune platelegs" },
  { id: 2, name: "Cannonball", nameLower: "cannonball" },
];

export const OSRS_ITEM_NAME_TO_ID = new Map<string, number>(
  OSRS_ITEMS.map((item) => [item.nameLower, item.id]),
);

export const OSRS_ITEM_ID_TO_NAME = new Map<number, string>(
  OSRS_ITEMS.map((item) => [item.id, item.name]),
);

/** Cache query key for individual OSRS item prices in TanStack Query. */
export function osrsItemQueryKey(itemId: number): string[] {
  return ["osrs", "item", itemId.toString()];
}
