export { DependencyGraph } from "./DependencyGraph";
export { ScopeManager } from "./ScopeManager";
export { Value, ValueType, numberValue, hexValue, bigIntValue, stringValue, uomValue, matrixValue, rowVectorValue, colVectorValue, rangeValue } from "./Value";
export type { MatrixData, MatrixEntry, RangeData } from "./Value";
export { createVM, executeBytecode } from "./VM";
export type { Bytecode } from "./VM";
export { VMCheckpointer } from "./VMCheckpoints";
export type { VMCheckpoint } from "./VMCheckpoints";
export { builtinFunctions, pluginFunctionRegistry, allocatePluginFunctionIndex } from "./VMBuiltins";
export { unifyUom, binaryOp } from "./VMConversion";
export { OpRegistry, sharedOpRegistry } from "./OpRegistry";
export type { VM } from "./OpRegistry";
export type { ExpressionRecord } from "./ScopeManager";
